apiVersion: v1
kind: Service
metadata:
  name: node-dockerapp
spec:
  type: NodePort
  selector:
    app: node-dockerapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-dockerapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-dockerapp
  template:
    metadata:
      labels:
        app: node-dockerapp
    spec:
      containers:
      - name: node-app
        image: chroops/express-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        imagePullPolicy: Never # Image should not be pulled

